// Every word in the picture of L01-1 "One Ant Can't Add", per language (?lang=en|zh). Numbers and wording are the
// cleared ones from ../FACTS.md (sections 2 and G) and ../SCRIPT.md. Captions: '|' starts the next caption of a
// line, '/' breaks it into two rows.
export const STR = {
  en: {
    strip: 'LLM SYSTEMS · CSE 291P · LECTURE 1',
    marquee: 'FREE ENTRY*',
    title: ['One ant', "can't add."],
    sum: '347 + 586 = ?',
    note0: ['Rehearse', 'more?'],
    anderson: { t: ['MORE IS', 'DIFFERENT'], sub: null, by: 'P. W. Anderson · Science, 1972', note: 'first given as a lecture in La Jolla, 1967' },
    curve: { t: 'ARITHMETIC · GPT-3', sub: 'modified arithmetic, BIG-Bench', y: 'accuracy', x: 'training compute →', k: '13B',
      foot: 'schematic · after Wei et al. 2022, Fig. 2A' },
    ops: 'operations, not speed', antFoot: '*parameters, not ants (our analogy)',
    tagCat: 'CAT: PARTIAL CREDIT', tagJudge: 'JUDGES: ALL OR NOTHING',
    mirage: ['…a Mirage?', 'Schaeffer, Miranda & Koyejo · NeurIPS 2023'],
    rule: { h: 'HOUSE RULE', t: ['BUDGET ≈', 'CAST × REHEARSAL'], s: ['budget = training compute · cast = parameters', 'rehearsal = training tokens'] },
    cast: 'CAST', reh: 'REHEARSAL', castV: ['175B', '280B', '530B'], rehV: ['300B', '300B', '270B'], unitC: 'parameters', unitR: 'tokens',
    years1: '2020–2021',
    noteR: ['REHEARSAL??'],
    year: '2022',
    upper: '280B · 300B tokens', lower: '70B · 1.4T tokens',
    banner: 'SAME BUDGET', bannerS: 'same training compute · Chinchilla 70B vs Gopher 280B · Hoffmann et al. 2022',
    noteRm: ['Rehearse', 'more.'],
    exam: '57-subject exam · MMLU, 5-shot',
    bill0: ['THE BILL'],
    bills: [['> $100,000,000', 'one frontier training run (est.)', 'e.g. Gemini Ultra ≈ $191M · Stanford AI Index 2024'],
      ['100,000 H100 GPUs', 'in one cluster', 'xAI Colossus, 2024 (xAI, NVIDIA)'],
      ['$500,000,000,000', 'over 4 years (planned)', 'Stargate Project, announced 21 Jan 2025']],
    years2: '2023–2025',
    noteCat: ['1% of $100M', '= $1M'],
    motto: { t: ['ACCURACY =', 'EFFICIENCY × RESOURCES*'], eff: 'EFFICIENCY', by: 'motto · Stanford CS336, Lecture 1 (2025)', law: 'a motto, not a law' },
    wrong: ['wrong reading:', 'SCALE IS ALL THAT MATTERS.'],
    fix: '→ ALGORITHMS THAT SCALE',
    prog: ['PROGRAMME', 'CSE 291P', 'LLM System Optimization', 'Prof. Yufei Ding · UC San Diego'],
    stamp: '*compute not included',
    dingBy: 'Prof. Yufei Ding · CSE 291P, Lecture 1',
    cap: {
      v01: "One ant can't add", v02: 'It could rehearse forever|Still one ant', v03: 'More ants', v04: 'Zero', v05: 'More',
      v06: 'Still zero', v07: 'More—', v08: '…it adds', v09: 'A physicist put it:/more is different',
      v10: 'Language models too:/near zero on arithmetic|then a jump/at 13B parameters', v11: 'Small models/won’t warn you',
      v12: 'Give partial credit,/like the cat,|and one paper finds/many jumps smooth out',
      v13: 'House rule: budget is/roughly cast × rehearsal', v14: 'Casts grew', v15: 'Rehearsal: 300B tokens', v16: '300B', v17: '270B',
      v18: 'Rehearsal’s for/small troupes', v19: 'Same budget:/a quarter of the cast|about 4x the rehearsal', v20: 'The small troupe won',
      v21: 'Double the cast,/double the rehearsal', v22: 'Budgets went industrial|One frontier run:/an estimated $100M+',
      v23: 'One plan: $500 billion', v24: 'Save 1% of one run:/a million dollars',
      v25: 'Stanford’s CS336 motto:|accuracy equals efficiency/times resources',
      d01: '“If you can make it larger,/then the idea is:|how can you efficiently/make it larger?”',
      v26: 'Efficiency: taught here', v27: 'Compute…', v28: '…not included',
    },
  },
  zh: {
    strip: '大模型系统 · CSE 291P · 第 1 讲',
    marquee: '免费入场*',
    title: ['一只蚂蚁', '不会算数'],
    sum: '347 + 586 = ?',
    note0: ['多排练？'],
    anderson: { t: ['多者异也'], sub: 'More Is Different', by: 'P. W. 安德森 ·《科学》· 1972', note: '最早是 1967 年在拉霍亚的一场讲座' },
    curve: { t: '算术题 · GPT-3', sub: '改版算术题，BIG-Bench', y: '准确率', x: '训练总运算量 →', k: '13B',
      foot: '示意 · 据 Wei 等 2022 图 2A' },
    ops: '总运算量，不是速度', antFoot: '*是参数，不是蚂蚁（比喻是我们的）',
    tagCat: '猫：给部分分', tagJudge: '评委：全对才给分',
    mirage: ['……是海市蜃楼吗？', 'Schaeffer 等 · NeurIPS 2023'],
    rule: { h: '剧场规定', t: ['预算 ≈', '演员 × 排练'], s: ['预算 = 训练算力 · 演员 = 参数', '排练 = 训练 token'] },
    cast: '演员', reh: '排练', castV: ['1750亿', '2800亿', '5300亿'], rehV: ['3000亿', '3000亿', '2700亿'], unitC: '参数', unitR: 'token',
    years1: '2020–2021',
    noteR: ['排练呢？？'],
    year: '2022',
    upper: '2800亿参数 · 3000亿 token', lower: '700亿参数 · 1.4万亿 token',
    banner: '同一笔预算', bannerS: '训练算力相同 · Chinchilla 700亿 vs Gopher 2800亿 · Hoffmann 等 2022',
    noteRm: ['多排练。'],
    exam: '57 科考试 · MMLU 5-shot',
    bill0: ['账单'],
    bills: [['> 1 亿美元', '训练一个顶级模型（估算）', '例：Gemini Ultra 约 1.91 亿美元 · 斯坦福 AI Index 2024'],
      ['10 万张 H100', '一个集群', 'xAI Colossus，2024（xAI、NVIDIA）'],
      ['5000 亿美元', '四年（计划）', 'Stargate 计划，2025 年 1 月 21 日宣布']],
    years2: '2023–2025',
    noteCat: ['1亿的1%', '= 100万'],
    motto: { t: ['准确率 =', '效率 × 资源*'], eff: '效率', by: '口号 · 斯坦福 CS336 第 1 讲（2025）', law: '是口号，不是定律' },
    wrong: ['错误读法：', '规模就是一切。'],
    fix: '→ 能放大的算法',
    prog: ['节目单', 'CSE 291P', '《大模型系统优化》', 'Yufei Ding 教授 · UC San Diego'],
    stamp: '*算力另计',
    dingBy: 'Yufei Ding 教授 · CSE 291P 第 1 讲（原声，中文为译文）',
    cap: {
      v01: '一只蚂蚁 不会算数', v02: '排练一万遍|也还是一只', v03: '多来点', v04: '零', v05: '再多', v06: '还是零', v07: '再多——',
      v08: '……会了！', v09: '物理学家安德森说/多，就不一样',
      v10: '大模型也是/算术题几乎零分|到130亿参数/突然跳起', v11: '小模型上 看不出来',
      v12: '像猫这样给部分分|有篇论文发现/很多“突然” 变成了“渐渐”',
      v13: '剧场规定/预算约等于演员乘排练', v14: '演员越请越多', v15: '排练：3000亿 token', v16: '3000亿', v17: '2700亿',
      v18: '排练？/小剧团才排练', v19: '同一笔预算/演员只要四分之一|排练约四倍', v20: '小剧团赢了',
      v21: '演员翻倍/排练也得翻倍', v22: '加量 又加价|训一个顶级模型/估计上亿美元',
      v23: '一个计划：5000亿美元', v24: '按一亿算 省1%/就是一百万美元',
      v25: '斯坦福一门课的口号|准确率 等于效率乘资源',
      d01: '“能做大，/接下来就要想：|怎么更高效地做大？”',
      v26: '效率 这门课教', v27: '算力嘛……', v28: '另计',
    },
  },
};
