#!/bin/bash
# riso look art (bake-off): flat risograph-palette drawings by Codex, separated into ink plates in film.js
cd "$(dirname "$0")/../../../../art"
STY="Style: a flat risograph-print illustration, like a two-colour screen-printed zine poster by a good illustrator: bold simple flat shapes, confident silhouettes, ONLY these flat ink colours: fluorescent pink #F04CB7, bright yellow #FFF028, medium blue #3A92C5, deep navy #203892, the paper white #F1EBE2, and the overprints orange-red (pink over yellow) and purple (pink over blue). Never use any green. No gradients, no airbrush, no textures, no grain, no halftone, no soft shading: shading only as flat shapes of another ink. No line thinner than 6 px; dark details and outlines are solid navy. No text, no letters, no numbers, no logos, no brand names."
GREEN="Background: perfectly flat solid pure green #00FF00 filling the whole image, no floor, no cast shadow, no gradient. Everything is in frame with a margin on every side, nothing cropped."
./gen.sh riso_gpu "A chunky modern gaming graphics card (a generic PC graphics card, no brand), seen from the front in a slight three-quarter view, long and horizontal: a navy shroud with angular pink and yellow accent stripes, two big round fans with blue blades, a short yellow gold edge connector along the bottom edge, a metal bracket at the left end. It looks powerful and a bit heroic. $STY $GREEN Landscape 1536x1024." &
./gen.sh riso_servers "A wall of data-center server racks seen straight on: four tall racks standing side by side and touching, each rack a navy frame filled with stacked flat server units in blue, every unit with a row of tiny square status lights in yellow and pink, a few cable bundles. Tall, imposing, symmetrical, fills the image. $STY $GREEN Portrait 1024x1536." &
./gen.sh riso_brain "A big AI brain: a rounded brain shape built from thick looping fluorescent-pink tubes (the folds of a brain), with small yellow and blue round nodes linked by short navy lines dotted over it like a neural network, a purple shadow side. No face. A clean bold icon-like shape that reads instantly as an AI brain. $STY $GREEN Square 1024x1024." &
./gen.sh riso_coders "Three programmers side by side at their laptops, front view, waist up, completely losing their minds with amazement: one with both hands on the head and the mouth wide open, one leaping up with arms thrown in the air, one with the hair blown back and eyes like saucers; burst and spark shapes around their heads. Varied people: different hair styles, glasses, a hoodie, a t-shirt; skin in a pale pink tint of the pink ink, hair in navy, purple or orange-red. Expressive comic faces drawn with solid navy shapes. They fill the width. $STY $GREEN Landscape 1536x1024." &
./gen.sh riso_chefs "A character sheet of SIX different chefs in two rows, all full body, front view, the same height and size, evenly spaced with wide clear green gaps between every figure (they must never touch). TOP ROW: the six chefs standing still and waiting, arms crossed or hands behind the back, calm. BOTTOM ROW: exactly the same six chefs in the same order, now cooking energetically: tossing a wok with orange-red flames, stirring a pot with steam, flipping a pan, chopping with a cleaver, whisking a bowl, holding up a sizzling skillet. Each chef wears a white jacket and a tall white toque (white = the paper colour #F1EBE2 with navy outlines) and an apron in pink, blue, navy or yellow; different faces, hair, moustaches, glasses; skin in a pale pink tint. Friendly, simple, readable at small size. $STY $GREEN Landscape 1536x1024." &
./gen.sh riso_ticket "A single blank restaurant order ticket: a tall slip of paper in the paper white #F1EBE2 with a zigzag torn bottom edge, a navy header band at the top, three faint blue ruled lines, held at the top by a yellow wooden clothes peg, slightly tilted. Completely empty, no writing. $STY $GREEN Portrait 1024x1536." &

# the kitchen backdrop (full bleed, no key)
./gen.sh riso_kitchen "A full-bleed restaurant kitchen backdrop, portrait, seen straight on, calm and simple so a crowd of small figures can stand in front of it: the upper half a wall of large square tiles in the pale tint of blue, a long navy range-hood band across the very top with a few round yellow lamps, a row of hanging pans and ladles in navy and purple along the hood, the lower third a long stainless counter in navy with a pink front edge. Large flat areas, low detail, no people. $STY Full bleed, no background colour around it. Portrait 1024x1536." &

wait