// Every word in the full line-art Strata film (?lang=en|zh): the hand lettering on the sheet and the captions.
// Captions: one entry per VO line (vo_lines.json ids); '|' splits a line into parts timed on the voice's word marks,
// '/' breaks a part into two rows. Numbers on screen come from SCRIPT.md section 5 (no new numbers here).
export const STR = {
  en: {
    // B0 cover, card, forum
    hook: ['A data-center AI', 'on ONE gaming card?'],
    hookTag: 'Strata · No. 2 on Hacker News, Oct 4',
    card: 'ONE gaming card',
    forumTitle: ['Strata: a 125B model', 'on a gaming PC'], forumStrata: 'Strata',
    forumDate: 'Oct 4, 2026',
    wow: ['WHAT?!', 'no way', 'how??', 'it RUNS?'],
    // B1 the pile of numbers
    count: '125,000,000,000', countUnit: 'numbers',
    years: 'count 1 per second: ~4,000 years',
    fits: 'what fits', card4090: 'RTX 4090 · 24 GB', x10: '×10', press: 'Strata', stillNo: "still won't fit!",
    // B2 who we are
    slip: 'pattern?', lab: 'Picasso Lab', labSub: "UC San Diego · Prof. Yufei Ding's lab",
    // B3 the kitchen
    quote: '“Think of a kitchen…”', quoteBy: "— Strata's author",
    chefs: '128 chefs', station: 'one station', model: '(Qwen3-235B, one of the models in our data)',
    ticket: 'one word', experts: 'experts', titles: ['soup chef', 'pastry chef'], q: '?',
    askQ: 'How do I make tomato-egg stir-fry?', ans: ['First,', 'beat', 'the', 'eggs', 'with', 'a', 'pinch', 'of', 'salt…'], ansSep: ' ',
    // B4-B5 upstairs, downstairs
    notHave: "doesn't have to", cardLabel: 'graphics card · small, fast', ramLabel: 'memory · big', stove: 'small, slow stove',
    slower: 'many × slower', lag: 'lag',
    // B6-B9 who stays upstairs, the score card
    who: 'Who stays upstairs?', strata: 'Strata',
    gridHead: ['out of 100 calls:', 'chef already upstairs?'],
    o8: ['Scores: our simulation on Qwen3-235B slips.', 'Not a test of Strata.'],
    quarter: 'room for 1/4',
    rows: [['①', 'blindfold', '25'], ['②', 'busiest', '51'], ['③', 'recent regulars', '77']],
    gradeF: 'F', double: 'double the blindfold', triple: '3× the blindfold',
    badge: '121', random23: 'random: 2-3', slice: 'one station, 40 words, our released data',
    again: 'again', reserved: 'reserved: 121',
    fine: ['Simulation on our released Qwen3-235B traces (71 requests, 9,082 generated tokens),',
      'not a run of Strata, whose model is different (512 experts per layer, 10 per token).',
      "Rules two and three are simple rules written for this video, not the paper's method.",
      "Speed claims are Strata's and the Hacker News poster's."],
    room2: 'room ×2', half: 'room for 1/2', rowsH: [['', 'blindfold', '50'], ['', 'recent regulars', '93']], gradeA: 'A',
    // B7 the order slips
    receipts: 'the receipts', models: ['DeepSeek-V3', 'Kimi K2', 'Llama 4 Maverick', 'Qwen3-235B'], requests: '24,000+ requests',
    paper: ['Patterns behind Chaos', 'Forecasting Data Movement for Efficient', 'Large-Scale MoE LLM Inference',
      'Yu, Guan, Yu, Zhou, Hu, Pei, Kang, Ding, Tsai'],
    award: ['Best Paper', 'Award', 'ISCA 2026'], isca: 'ISCA: a computer-architecture conference',
    cousin: ["older, bigger cousin", "of Strata's Qwen"], calls: '≈ 6,800,000 chef calls', pretend: 'pretend kitchen = our simulation',
    // B10-B12
    smarter: 'same hardware, used smarter', cheaper: 'cheaper', ownPC: 'on your own computer', private: 'stays on your desk',
    sys: '(this is called systems research)',
    open: 'open data', link: 'link in first reply', you: 'you?',
    chaos: 'chaos?', pattern: 'pattern.',
    // B13 end card
    end: ['Picasso Lab · UC San Diego', '@PicassoLabUCSD', 'paper + data: first reply'],
    cap: {
      b01: 'This AI is too big/for a gaming card.',
      b02: 'A free program called Strata/runs it on a gaming PC anyway.|Programmers lost their minds.',
      b03: 'An AI model is/a giant pile of numbers.|The one Strata runs, Qwen,/has 125 billion.',
      b04: "Stored the usual way, that's/ten times what an RTX 4090 holds.|Strata squeezes it hard.|Still won't fit.",
      b05: 'So how does it run?|Part of the answer is/a pattern our lab measured.|We\'re Picasso Lab,/at UC San Diego.',
      b06: "Strata's author explains it/with a kitchen.|Let's go in.",
      b07: 'Picture a giant restaurant.|The one we\'ll follow today has/128 chefs at every station.',
      b08: 'For each word the AI writes,/the slip calls just eight of them.|The next word calls its own eight.',
      b09: 'Engineers call them experts.|Experts in what?|Nothing as simple as/soup or pastry:|the AI worked out on its own/whom to call.',
      b10: 'How does it fit, then?|It doesn\'t have to.|Each word needs only a few chefs,|so the busiest work upstairs,/in a small, fast kitchen:|the graphics card.',
      b11: 'Everyone else waits downstairs/in a big room:|the computer\'s memory.|They can cook there too,/on a small, slow stove.',
      b12: 'The catch: cooking downstairs,/or running a chef up the stairs,|is many times slower/than using one already upstairs.',
      b13: 'The more chefs a word needs/from downstairs,|the slower the answer comes out.',
      b14: 'So tricks like Strata\'s/come down to one question:|who stays upstairs?',
      b15: 'Let\'s keep score:|out of a hundred calls,/how many find their chef upstairs?|Say upstairs fits a quarter.|Rule one: pick blindfolded.|Twenty-five.',
      b16: 'Can you beat the blindfold?|We didn\'t have to guess.|Our lab kept the order slips.',
      b17: 'DeepSeek, Kimi, Llama, Qwen:|who got called, for every word.|Our paper on them,/Patterns behind Chaos,|won a Best Paper Award/this summer.',
      b18: 'We took slips from Qwen3,|an older, bigger cousin/of Strata\'s model,|and ran a sample/through a pretend kitchen.',
      b19: 'Watch chef 121.|Nineteen calls in forty words.|Random would be two or three.',
      b20: 'Rule two:/keep the busiest chefs upstairs.|Fifty-one.|Already double the blindfold.',
      b21: 'Look closer:|121, again, and again.|Whoever was just called/tends to be called again.',
      b22: 'Rule three:/keep the recent regulars.|Seventy-seven.|Triple the blindfold.',
      b23: 'Strata\'s own upstairs/works a bit like this:|while you chat,/it keeps learning who\'s busy.',
      b24: 'Now double the room upstairs.|Blindfold: fifty.|Recent regulars: ninety-three.',
      b25: 'Only seven calls in a hundred/still need downstairs.|Less work downstairs,/faster answers.',
      b26: 'Same hardware, used smarter.|That\'s one way big AI gets cheaper,|and moves onto your own computer,|where what you type/never leaves your desk.',
      b27: 'The slips are public.|Maybe you\'ll build the next Strata.',
      b28: 'It looks like chaos.|It\'s a pattern.|The trick isn\'t fitting/every chef upstairs.|It\'s guessing who\'s next.',
    },
  },
  zh: {
    hook: ['1250 亿参数的千问大模型', '塞进一张游戏显卡？'],
    hookTag: 'Strata · 国外程序员论坛 Hacker News 当日第 2',
    card: '一张游戏显卡',
    forumTitle: ['Strata：1250 亿参数模型', '跑在游戏电脑上'], forumStrata: 'Strata',
    forumDate: '2026 年 10 月 4 日',
    wow: ['啊？！', '不可能', '真的假的', '跑起来了？'],
    count: '1250 亿', countUnit: '个数',
    years: '一秒数一个，要数近四千年',
    fits: '显卡装得下的', card4090: 'RTX 4090 · 24 GB', x10: '×10', press: 'Strata', stillNo: '还是塞不下！',
    slip: '规律？', lab: 'Picasso 实验室', labSub: '加州大学圣地亚哥分校 · Yufei Ding 教授课题组',
    quote: '“可以想象一个厨房……”', quoteBy: '—— Strata 作者',
    chefs: '128 位厨师', station: '一个灶台', model: '（千问 Qwen3-235B，我们数据里的模型之一）',
    ticket: '一个词', experts: '专家', titles: ['川菜', '粤菜'], q: '？',
    askQ: '西红柿炒鸡蛋怎么做？', ans: ['先', '把', '鸡', '蛋', '打', '散，', '加', '一', '小', '撮', '盐……'], ansSep: '',
    notHave: '不用全塞', cardLabel: '显卡：小，但快', ramLabel: '内存条：大', stove: '小灶，火慢',
    slower: '慢好多倍', lag: '卡',
    who: '楼上留谁？', strata: 'Strata',
    gridHead: ['叫 100 次：', '人正好在楼上的有几次？'],
    o8: ['分数：我们在千问 Qwen3-235B 单子上的模拟，', '不是对 Strata 的实测。'],
    quarter: '楼上放 1/4',
    rows: [['①', '蒙眼', '25 分'], ['②', '留最忙的', '51 分'], ['③', '留熟面孔', '77 分']],
    gradeF: '不及格', double: '蒙眼的两倍', triple: '蒙眼的三倍',
    badge: '121', random23: '随机：两三次', slice: '一个灶台、40 个词，我们公开的数据',
    again: '又是你', reserved: '121 专座',
    fine: ['基于我们公开的 Qwen3-235B 数据模拟（71 个请求、9082 个生成 token），',
      '并非实测 Strata；Strata 用的模型不同（每层 512 位专家、每词 10 位）。',
      '第二、三种规则是为本视频写的简单规则，不是论文方法。',
      '速度说法来自 Strata 作者和 Hacker News 发帖人。'],
    room2: '楼上扩建一倍', half: '楼上放 1/2', rowsH: [['', '蒙眼', '50 分'], ['', '留熟面孔', '93 分']], gradeA: '优',
    receipts: '单子都在', models: ['DeepSeek-V3', 'Kimi K2', 'Llama 4 Maverick', 'Qwen3-235B'], requests: '两万四千多条提问',
    paper: ['Patterns behind Chaos', '（混乱背后的规律）', 'Forecasting Data Movement for Efficient Large-Scale MoE LLM Inference',
      'Yu, Guan, Yu, Zhou, Hu, Pei, Kang, Ding, Tsai'],
    award: ['最佳', '论文奖', 'ISCA 2026'], isca: 'ISCA：计算机体系结构会议',
    cousin: ['千问家老大哥', ''], calls: '约 680 万次点名', pretend: '模拟厨房 = 我们的模拟',
    smarter: '同样的硬件，用得更聪明', cheaper: '更便宜', ownPC: '在你自己的电脑上', private: '不出家门',
    sys: '（这叫“系统研究”）',
    open: '数据公开', link: '链接见评论区', you: '你？',
    chaos: '乱？', pattern: '有规律。',
    end: ['Picasso 实验室 · 加州大学圣地亚哥分校', '《算力另计》热点篇', '论文和数据：评论区'],
    cap: {
      b01: '这个 AI，一张游戏显卡装不下',
      b02: '可免费软件 Strata，偏偏在/一台游戏电脑上把它跑起来了|国外程序员直接炸了',
      b03: 'AI 模型，说白了/就是一大堆数字|Strata 跑的是阿里的千问，/足足 1250 亿个',
      b04: '正常存，/得十多张 4090 才装得下|Strata 使劲压缩过，/一张卡还是塞不下',
      b05: '那它怎么跑起来的？|答案里，/有我们测到的一个规律|我们是加州大学圣地亚哥分校的/Picasso 实验室',
      b06: 'Strata 的作者自己打了个比方：/厨房|进去看看',
      b07: '想象一家超大的餐厅|今天跟拍的这一家，/每个灶台站着 128 位厨师',
      b08: 'AI 每写一个词，/单子上只叫八位上手|下一个词，再重新点八位',
      b09: '工程师管他们叫“专家”|专什么？|可不是川菜粤菜这么简单|叫谁，是 AI 自己琢磨出来的',
      b10: '那到底怎么塞进去的？|根本不用全塞|每个词只用得着几位，|最忙的就待在楼上的小厨房：|地方小，手脚快|这就是显卡',
      b11: '其余的人，都待在楼下的大屋子里，|也就是电脑的内存条|楼下也能做菜，只是灶小火慢',
      b12: '麻烦就在这儿：|在楼下小灶上做，/或者把人叫上楼，|都比用楼上现成的慢好多倍',
      b13: '一个词要的人里，/楼下的越多，|回答就出得越慢',
      b14: '所以 Strata 这类办法，|说到底就一个问题：|楼上留谁？',
      b15: '打个分：|叫一百次，/几次人正好在楼上？|假设楼上放得下四分之一|第一种，蒙眼随便挑：|25 分',
      b16: '能比蒙眼强吗？|不用猜|我们实验室，留着后厨的单子',
      b17: 'DeepSeek、Kimi、Llama、千问：|每个词叫了谁，全记着|写成的论文《混乱背后的规律》，|今年拿了最佳论文奖',
      b18: '我们挑了千问家老大哥的/一部分单子，|在模拟厨房里重新走了一遍',
      b19: '盯住 121 号：|四十个词里，他被叫了十九次|要是随机，也就两三次',
      b20: '第二种：把最忙的几位留在楼上|51 分，|已经是蒙眼的两倍',
      b21: '再细看：|121 号，又是你，又是你|刚被叫过的，/往往很快又被叫到',
      b22: '第三种：留最近的熟面孔|77 分，|蒙眼的三倍',
      b23: 'Strata 自己的楼上，/也是这么留人的：|你聊着，它一直在学谁最忙',
      b24: '楼上再扩建一倍：|蒙眼 50 分，|留熟面孔 93 分',
      b25: '一百次点名，/只剩 7 次要找楼下|楼下的活少了，回答就快',
      b26: '同样的硬件，用得更聪明|大模型要变便宜、/搬进你自己的电脑，|聊什么都不出家门，|少不了这类功夫',
      b27: '单子全部公开|说不定，/下一个 Strata 就出自你手',
      b28: '看着是一团乱麻，|其实有规律|诀窍不是把人全塞上楼，|而是猜准下一个轮到谁',
    },
  },
};
