#!/bin/bash
# line look art (bake-off): black ink line drawings by Codex on pure white; ink.py turns them into ink-on-alpha
# sprites with a paper fill and a "pen" reveal map. usage: ./art.sh 1 (scene art) | ./art.sh 2 (chef poses, master as ref)
cd "$(dirname "$0")/../../../../art"
STY="Style: a hand-drawn line illustration for a friendly science-explainer, black ink only on a pure white (#FFFFFF) background. Confident, clean, continuous pen lines of even medium-bold weight (like a 1.0 mm fineliner), slightly hand-made but tidy, every shape drawn with closed outlines; NO shading, NO hatching, NO grey tones, NO colour, NO fills, NO solid black areas, NO gradients, NO paper texture, NO text, NO letters, NO numbers, NO logos, NO border, NO frame, NO drop shadow. The background must be flat pure white everywhere. Everything in frame with a margin on every side, nothing cropped."
if [ "$1" = 1 ]; then
./gen.sh line_servers "A wall of data-center server racks seen straight from the front: five tall racks side by side touching each other, each rack packed with many stacked thin server units (horizontal slabs with small vent slots and tiny round status lights drawn as small circles), a few cable bundles looping on top. Portrait image 1024x1536, the racks fill about 90% of the width and 85% of the height, centred. $STY" &
./gen.sh line_gpu "A big modern gaming graphics card (a generic one, no brand) seen in a gentle three-quarter view from the front-left, lying horizontally: three large round cooling fans with curved blades on the shroud, a slim metal bracket with ports on the left end, the gold-finger connector along the bottom edge drawn as a row of small rectangles. Landscape image 1536x1024, the card fills about 85% of the width, centred. $STY" &
./gen.sh line_brain "An AI model drawn as a big friendly brain: a rounded brain shape with clear simple folds, and a few small round nodes connected by short straight links (like a circuit or neural network) sitting on top of the folds. No face. Simple, iconic, reads instantly as an AI brain. Square image 1024x1024, the brain fills about 75% of the width, centred. $STY" &
./gen.sh line_coders "Four young programmers (mixed men and women, hoodies, glasses, headphones) sitting behind open laptops in a row, all reacting with total shock and amazement: hands on heads, jaws dropped, eyes wide, one standing up with arms thrown up, hair standing up, small motion strokes around their heads. Seen from the front, waist up. Landscape image 1536x1024, the group fills about 92% of the width. Friendly cartoon line style, simple faces with dot eyes. $STY" &
./gen.sh line_chef "One friendly cartoon chef, full body, standing straight facing the viewer, arms relaxed at the sides: a tall pleated chef's toque hat, a simple round face with dot eyes and a small smile, a double-breasted chef jacket with two rows of buttons, a neckerchief, a long apron to the knees, simple trousers and shoes. A master character design that will be repeated many times at small size, so keep it simple, bold and clear, few details. Portrait image 1024x1536, the chef fills about 85% of the height, centred. $STY" &
sleep 20
./gen.sh line_kitchen "A big professional restaurant kitchen interior, empty of people, seen from the front, symmetrical: along the top a long steel rail with many hanging pots, pans, ladles and whisks; a big extractor hood; a wall of large square tiles; along the bottom a long row of stoves with burners and oven doors. Portrait image 1024x1536, fills the frame, with a large empty floor area in the middle third. Keep the tile wall light and sparse. $STY" &
./gen.sh line_ticket "A single restaurant order ticket: a narrow tall slip of paper with a zig-zag torn bottom edge, held at the top by a small metal bulldog clip, slightly curled at one corner, with a big empty blank area in the middle (leave it empty for writing later). Portrait image 1024x1536, the slip fills about 75% of the height, centred. $STY" &
./gen.sh line_burst "A comic explosion burst made only of ink strokes: radiating straight and slightly curved speed lines bursting outward from an empty centre, small stars, small exclamation marks, small up-arrows and little spark marks flying outward. The centre area (about 40% of the image) stays empty white. Square image 1024x1024. $STY" &
./gen.sh line_forum "A hand-drawn web forum thread window, generic and invented (no real website): a browser-like window with a rounded rectangle frame and three small circles on the top bar; inside, at top, a big empty space for a thread title next to an up-vote arrow and a down-vote arrow stacked vertically; below it four comment rows, each with a small round avatar circle, two or three empty horizontal placeholder lines (just lines, no writing), and a small up-arrow. Portrait image 1024x1536, the window fills about 88% of the width, centred. Leave the placeholder spaces empty. $STY" &
wait
fi
if [ "$1" = 2 ]; then
export REFNOTE="The attached image is the master character design of the chef (black ink line art on white): keep exactly the same character, proportions, outfit and line style; only change the pose as described."
REF=src/line_chef.png
./gen.sh line_chef_wait "The same chef, full body, front view, standing and waiting patiently with both hands clasped behind the back, a calm slightly bored face. Portrait image 1024x1536, the chef fills about 85% of the height, centred. $STY" $REF &
./gen.sh line_chef_wait2 "The same chef, full body, front view, standing and waiting with the arms crossed over the chest, holding a ladle in one hand, a patient face. Portrait image 1024x1536, the chef fills about 85% of the height, centred. $STY" $REF &
./gen.sh line_chef_cook "The same chef, full body, front view, cooking energetically: holding a frying pan up in one hand and tossing food (a few round pieces flying in an arc above the pan), the other arm out for balance, a happy focused face, small flame strokes under the pan, small motion strokes. Portrait image 1024x1536, the chef fills about 85% of the height, centred. $STY" $REF &
./gen.sh line_chef_cook2 "The same chef, full body, front view, cooking energetically: stirring a big round cooking pot held in front of the body with a long spoon, curly steam lines rising from the pot, a cheerful busy face, small motion strokes. Portrait image 1024x1536, the chef fills about 85% of the height, centred. $STY" $REF &
wait
fi
