#!/usr/bin/env python3
"""Footer globe travellers: key the painted green-screen art (home/footer-src/tiga.png, ark.png - generated by the user
with ChatGPT) into small RGBA sprites, nose turned to +x, under home/static/globe/.   python3 home/footer-src/sprites.py
"""
import os
import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'static', 'globe')
# name: (degrees to turn the art so the nose points right, output width)
SPR = {'tiga': (5.8, 160), 'ark': (19.5, 160)}   # PIL turns counter-clockwise

for name, (rot, width) in SPR.items():
    im = np.asarray(Image.open(os.path.join(HERE, name + '.png')).convert('RGB')).astype(np.float32) / 255
    r, g, b = im[..., 0], im[..., 1], im[..., 2]
    gd = g - np.maximum(r, b)                                   # green dominance
    a = 1 - np.clip((gd - 0.10) / 0.45, 0, 1)                   # 0 on the screen, 1 on the figure, soft glow edges
    spill = np.maximum(0, g - np.maximum(r, b))                 # despill: pull green down to the larger of red / blue
    rgb = np.stack([r, g - spill, b], -1)
    # an edge pixel was blended with green: un-premultiply what is left of the colour
    rgb = np.clip(rgb / np.maximum(a, 0.05)[..., None] * np.minimum(1, a * 4)[..., None], 0, 1)
    img = Image.fromarray((np.dstack([rgb, a]) * 255 + 0.5).astype(np.uint8), 'RGBA')
    img = img.rotate(rot, resample=Image.BICUBIC, expand=True)
    img = img.crop(img.getchannel('A').point(lambda v: 255 if v > 8 else 0).getbbox())
    h = round(img.height * width / img.width)
    img = img.resize((width, h), Image.LANCZOS)
    p = os.path.join(OUT, name + '.png')
    img.save(p, optimize=True)
    print(name, img.size, os.path.getsize(p), 'bytes')
