#!/usr/bin/env python3
"""Download candidate webfonts (woff2) from Google Fonts and write fonts/fonts.css.

Run once (needs network). Afterwards renders are fully offline: scenes load
/pv/fonts/fonts.css, which only references the local woff2 files.

    python3 tools/fetch_fonts.py
"""
import hashlib
import json
import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "fonts")
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")

# role -> css2 family spec. Variable axes are requested as ranges so one woff2
# per subset covers every weight.
FAMILIES = {
    "serif (refined)": "Fraunces:ital,opsz,wght@0,9..144,100..900;1,9..144,100..900",
    "serif (display)": "Instrument+Serif:ital@0;1",
    "sans (clean)": "Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900",
    "hand (pen)": "Caveat:wght@400..700",
    "hand (marker)": "Permanent+Marker",
    "mono": "JetBrains+Mono:ital,wght@0,100..800;1,100..800",
}
KEEP_SUBSETS = {"latin", "latin-ext", "greek", "math", "symbols"}


def fetch(url, binary=False):
    """Return (data, None) or (None, error)."""
    try:
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=60) as r:
            data = r.read()
        return (data if binary else data.decode("utf-8")), None
    except Exception as e:  # noqa: BLE001
        return None, f"fetch {url}: {e}"


def process_family(spec):
    """Download one family. Returns (list_of_css_blocks, None) or (None, err)."""
    css, err = fetch(f"https://fonts.googleapis.com/css2?family={spec}&display=block")
    if err:
        return None, err
    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*{[^}]*})", css)
    out = []
    for subset, block in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        m = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not m:
            continue
        url = m.group(1)
        fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        style = re.search(r"font-style:\s*(\w+)", block).group(1)
        slug = re.sub(r"[^a-z0-9]+", "-", fam.lower()).strip("-")
        fname = f"{slug}-{style}-{subset}-{hashlib.sha1(url.encode()).hexdigest()[:8]}.woff2"
        path = os.path.join(OUT, fname)
        if not os.path.exists(path):
            data, err = fetch(url, binary=True)
            if err:
                return None, err
            with open(path, "wb") as f:
                f.write(data)
        out.append(f"/* {subset} */\n" + block.replace(url, fname))
    return out, None


def main():
    os.makedirs(OUT, exist_ok=True)
    css_parts = ["/* Generated by tools/fetch_fonts.py - local copies of Google Fonts (OFL). */\n"]
    manifest = {}
    for role, spec in FAMILIES.items():
        blocks, err = process_family(spec)
        if err:
            print("ERROR", err, file=sys.stderr)
            return 1
        fam = spec.split(":")[0].replace("+", " ")
        manifest[fam] = role
        css_parts.append(f"/* ===== {fam} - {role} ===== */")
        css_parts.extend(blocks)
        print(f"{fam:18s} {role:18s} {len(blocks)} faces")
    with open(os.path.join(OUT, "fonts.css"), "w") as f:
        f.write("\n".join(css_parts) + "\n")
    with open(os.path.join(OUT, "fonts.json"), "w") as f:
        json.dump(manifest, f, indent=2)
    return 0


if __name__ == "__main__":
    sys.exit(main())
