#!/bin/bash
# L01-1 art, batch 1: the cat poses, the hero ant, and the set pieces (all Codex, keyed with key.py)
cd "$(dirname "$0")"
REF_FELT=cut/felt_cat_note.png
CAT_MAT="Material: a handmade stop-motion puppet made of felt - needle-felted white wool body with a soft fuzzy surface and visible fibres, flat cut-felt pieces for the inner ears, nose and eyelids with tiny visible hand stitches along the seams, a red wool felt beret with a little stalk on top, small round amber-brown glass-bead eyes with a bright highlight, exactly like the attached felt puppet. It must look like a real handmade object photographed in a studio, not a 3D render and not a drawing. Soft warm key light from the upper left, gentle soft shadows on the puppet itself only."
ANT_MAT="Material: a small handmade felt puppet of an ant for a toy paper theatre: dark chocolate-brown wool felt body in three rounded segments (head, thorax, abdomen) with soft fuzzy fibres and tiny pale hand stitches along the seams, two shiny black glass-bead eyes with a white highlight, short bendable antennae of brown pipe cleaner with a small felt ball on each tip, six thin legs of brown pipe cleaner, a friendly simple face with a small embroidered smile. It must look like a real handmade object photographed in a studio, not a 3D render, not a drawing, and not resembling any character from an existing film. Soft warm key light from the upper left, gentle soft shadows on the puppet itself only."
PROP="It must look like a real handmade object for a toy paper theatre, photographed in a studio: visible paper fibre or wool fibre, slight hand-cut irregularity, soft warm key light from the upper left, shading on the object only."
GREEN="Background: perfectly flat solid pure green #00FF00 filling the whole image, no floor, no cast shadow on the background, no gradient, no vignette. The whole object is in frame with a margin on every side, centred, nothing cropped. No text, no letters, no numbers, no logo, no frame."
run() { ./gen.sh "$@"; }
# cats (reference: the felt cat)
run felt_cat_back "A full-body felt cat puppet sitting with its back three-quarters turned to the viewer, looking back over its shoulder straight at the camera with a deadpan, half-lidded, unimpressed expression and a flat stitched mouth, tail curled beside it. $CAT_MAT $GREEN Portrait 1024x1536." $REF_FELT &
run felt_cat_slap "A full-body felt cat puppet standing on its hind legs in side three-quarter view facing right, one front paw raised high and pushed forward mid-slap, palm out, as if slapping a note onto a wall at its own head height; the other paw on its hip; smug half-lidded eyes. $CAT_MAT $GREEN Portrait 1024x1536." $REF_FELT &
run felt_cat_pen "A full-body felt cat puppet standing on its hind legs in side three-quarter view facing right, holding a plain red felt-tip marker (red barrel, cap off, no writing on it) in its right front paw, the tip touching an invisible surface in front of it mid-stroke, concentrating, tongue tip slightly out. $CAT_MAT $GREEN Portrait 1024x1536." $REF_FELT &
run felt_cat_stamp "A full-body felt cat puppet standing on its hind legs, front view, both front paws pressing a small wooden rubber stamp with a round wooden knob straight down onto an invisible surface at chest height, eyes closed with deep satisfaction, small closed smile. The stamp's rubber face is hidden (pressed down). $CAT_MAT $GREEN Portrait 1024x1536." $REF_FELT &
# the hero ant (no reference: it sets the design)
run felt_ant_card "A full-body felt ant puppet standing upright on its four back legs, front view, proudly holding a blank plain white square card (thin cardstock, completely empty) above its head with its two front legs. $ANT_MAT $GREEN Portrait 1024x1536." &
wait
# set pieces
run stage_inside "A photograph looking straight into the stage box of a handmade toy paper theatre, filling the whole frame edge to edge (no proscenium, no curtains, no frame around it): the back wall is a painted cardstock backdrop of a deep midnight-blue night sky with a soft lighter haze near the horizon and a few tiny painted stars, the floor is a stage of light-brown cardstock planks with visible paper fibre, slightly worn, receding in perspective toward the backdrop; plain dark cardstock wings at the far left and right edges. The stage is EMPTY: no figures, no props, no text. Lit softly from above by a single warm theatre spotlight making a pool of light on the floor centre. Real handmade object, macro photography, slight depth of field. Portrait 1024x1536." &
run curtain_closed "A pair of heavy red wool-felt theatre curtains for a toy paper theatre, fully CLOSED and meeting in the middle, hanging straight down in soft vertical folds, a thin gold thread trim along the bottom hem, top edge straight (hung from a rod that is not shown). The curtains fill about 80 percent of the image width. $PROP $GREEN Portrait 1024x1536." &
run risers "Three-tier bleachers (risers) for a toy paper theatre, made of folded cream cardstock with each step edged in a thin painted teal stripe, seen from the front and slightly above, wide and low, EMPTY (nothing standing on them). $PROP $GREEN Landscape 1536x1024." &
run judge_paddle "One round judge's score paddle for a toy paper theatre: a blank plain white circular cardstock disc with a thin gold painted rim, glued onto a thin wooden stick (like a lollipop), front view, the disc completely blank, the stick pointing straight down. $PROP $GREEN Portrait 1024x1536." &
run flip_easel "A small wooden easel for a toy paper theatre holding a flip-card stand: a stack of blank white cardstock cards bound at the top with two metal rings (like a desk flip chart), front view, the front card completely blank. $PROP $GREEN Portrait 1024x1536." &
wait
run light_bar "A theatre lighting bar for a toy paper theatre: a long thin black-painted wooden batten with a row of seven tiny theatre spotlights made of black card and brass, each with a coloured gel (amber, pink, blue), lamps switched off, seen from the front and slightly below, horizontal. $PROP $GREEN Landscape 1536x1024." &
run sticky_note "One plain square yellow sticky note, slightly curled up at the bottom edge, completely blank, photographed flat from the front with a soft shadow only under the curl. $PROP $GREEN Square 1024x1024." &
run envelope "One plain kraft-brown paper envelope, closed, flap at the top, seen from the front, completely blank, slightly creased. $PROP $GREEN Landscape 1536x1024." &
wait
