// Every word in the Strata hot-topic film (?lang=en|zh). Numbers: ../NOTES.md (our released Qwen3-235B traces).
export const STR = {
  en: {
    hook: ['125B MoE', 'on ONE RTX 4090?'], hookTag: '“Strata”, on the Hacker News front page · Oct 2026',
    board: 'ONE LAYER · 128 EXPERTS', legendGpu: 'on the GPU (32 fit)', legendRam: 'in system RAM',
    random: 'IF PICKS WERE RANDOM', real: 'REAL TRACES · Qwen3-235B', hit: 'GPU hit rate', times: '3×',
    fine: 'simulation on our released traces · 71 requests, 9,082 tokens · not a run of Strata',
    pcie: { t: 'COPYING IS SLOW', ram: 'SYSTEM RAM', gpu: 'GPU', link: 'PCIe 4.0 ≈ 25 GB/s', expert: '1 expert ≈ 19 MB (Qwen3-235B, FP8)' },
    cost: '≈ 10.6 GB per token → ≈ 2 tokens/s at the PCIe limit',
    bars: { t: 'GPU HIT RATE BY POLICY', a: 'GPU holds 1/4 (32 of 128)', b: 'GPU holds 1/2 (64 of 128)', p: ['random', 'popular', 'LRU', 'predictor'],
      speed: 'PCIe limit: LRU ≈ 17 tok/s → predictor ≈ 25 tok/s',
      fine: 'simulation on our released Qwen3-235B traces · predictor = a simple recency model for this post, not the paper’s method · tok/s = PCIe transfer bound, not measured' },
    paper: ['Patterns behind Chaos', 'Forecasting Data Movement for Efficient', 'Large-Scale MoE LLM Inference', 'ISCA 2026 · Best Paper'],
    data: 'traces: huggingface.co/datasets/core12345/MoE_expert_selection_trace',
    end: ['LAB · UC SAN DIEGO · PROF. YUFEI DING', '@PicassoLabUCSD'],
    cap: { h1: '125B parameters/on one gaming GPU?', h2: 'The trick: most experts/live in system memory', h3: 'Each token uses only a few,/copied over just in time',
      h4: 'If picks were random,/a GPU holding a quarter|would miss 3 times out of 4', h5: 'They’re not.|On our released Qwen3 traces,/the same space hits 77%',
      h6: 'Patterns behind chaos./Our ISCA ’26 best paper',
      p1: 'But copying is slow:|one expert ≈ 19 MB,/PCIe ≈ 25 GB per second', p2: 'That’s 10+ GB per token:/about 2 tokens a second',
      p3: 'Plain LRU already gets 75%.|Predicting from recent use/does a little better',
      p4: 'With half the experts on the GPU,/prediction cuts copying by a third|≈17 → 25 tokens per second/at the PCIe limit', p5: 'The traces are open./Links below' },
  },
  zh: {
    hook: ['1250亿参数', '一张 4090 就能跑？'], hookTag: '“Strata” 登上 Hacker News 首页 · 2026 年 10 月',
    board: '一层 · 128 个专家', legendGpu: '在显卡上（放得下 32 个）', legendRam: '在内存里',
    random: '假如专家随机挑选', real: '真实数据 · Qwen3-235B', hit: '显卡命中率', times: '3×',
    fine: '基于我们公开的数据模拟 · 71 个请求、9082 个 token · 并非实测 Strata',
    pcie: { t: '搬运很慢', ram: '内存', gpu: '显卡', link: 'PCIe 4.0 ≈ 25 GB/秒', expert: '一个专家 ≈ 19 MB（Qwen3-235B，FP8）' },
    cost: '每个词要搬 ≈ 10.6 GB → PCIe 上限约每秒 2 个词',
    bars: { t: '不同策略的显卡命中率', a: '显卡放 1/4（128 个里放 32 个）', b: '显卡放 1/2（128 个里放 64 个）', p: ['随机', '只放热门', 'LRU', '预测'],
      speed: 'PCIe 上限：LRU 约每秒 17 个词 → 预测约 25 个',
      fine: '基于我们公开的 Qwen3-235B 数据模拟 · “预测”是为本视频写的简单近期模型，并非论文方法 · 速度为 PCIe 搬运上限，非实测' },
    paper: ['混乱背后的规律', 'Patterns behind Chaos: Forecasting Data', 'Movement for Efficient Large-Scale MoE LLM Inference', 'ISCA 2026 · 最佳论文'],
    data: '数据：huggingface.co/datasets/core12345/MoE_expert_selection_trace',
    end: ['LAB · UC SAN DIEGO · PROF. YUFEI DING', '《算力另计》热点篇'],
    cap: { h1: '一张游戏显卡/跑1250亿参数的大模型？', h2: '秘诀是/大部分专家其实放在内存里', h3: '每个词只用到其中几个/用到再搬上显卡',
      h4: '如果专家是随机选的/显卡放下四分之一|四次里有三次要现搬', h5: '但它们不是随机的|在我们公开的Qwen3数据上/同样的空间 命中率77%',
      h6: '混乱背后有规律/我们的ISCA 2026最佳论文',
      p1: '可搬运很慢|一个专家约19MB/PCIe每秒只能搬约25GB', p2: '每个词要搬10GB以上/一秒只能出两个词左右',
      p3: '普通LRU缓存就有75%|按最近使用来预测/还能再高一点',
      p4: '显卡放一半专家时/预测把搬运量砍掉三分之一|PCIe上限/每秒约17个词→25个', p5: '数据全部公开/链接在评论区' },
  },
};
